### PR TITLE
Bump freedesktop version to 21.08

### PR DESCRIPTION
**Pull request by BryanQuigley**

### CODE REVIEW

**Comment by Frinksy** [comment]
It seems rust-stable for 21.08 was released recently, hopefully rust-nightly for 21.08 will follow soon

**Comment by hfiguiere** [comment]
rust-nightly  for 21.08 should be available soon (as soon as it is built)

**Comment by Frinksy** [comment]
bot, build

**Comment by Frinksy** [comment]
Thanks!

**Pull request merged**
